---
# Base Configuration:
homeassistant: !include conf/homeassistant.yaml

# Core Configuration
conversation:
default_config:
frontend: !include conf/frontend.yaml
http: !include conf/http.yaml
influxdb: !include conf/influxdb.yaml
logger: !include conf/logger.yaml
lovelace:
panel_iframe: !include conf/panel-iframe.yaml
python_script:
recorder: !include conf/recorder.yaml
stream:
scene: !include scenes.yaml

# Integrations:
almond: !include conf/almond.yaml
binary_sensor: !include conf/binary_sensors.yaml
ffmpeg: !include conf/ffmpeg.yaml
google: !include conf/google.yaml
hacs: !include conf/hacs.yaml
ifttt: !include conf/ifttt.yaml
mqtt: !include conf/mqtt.yaml
nest: !include conf/nest.yaml
notion: !include conf/notion.yaml
notify: !include conf/notifiers.yaml
proximity: !include conf/proximity.yaml
zone: !include conf/zones.yaml
