---
# Base Configuration:
homeassistant: !include conf/homeassistant.yaml

# Core Configuration
conversation:
default_config:
frontend: !include conf/frontend.yaml
http: !include conf/http.yaml
logger: !include conf/logger.yaml
lovelace:
panel_custom: !include conf/panel-custom.yaml
panel_iframe: !include conf/panel-iframe.yaml
recorder: !include conf/recorder.yaml
stream:
scene: !include scenes.yaml
script: !include conf/scripts.yaml

# Components:
almond: !include conf/platforms/almond.yaml
cloud: !include_dir_merge_named conf/cloud/
emulated_hue: !include conf/platforms/emulated-hue.yaml
ffmpeg: !include conf/platforms/ffmpeg.yaml
google: !include conf/platforms/google.yaml
group: !include_dir_named conf/groups/
ifttt: !include conf/platforms/ifttt.yaml
input_boolean: !include_dir_merge_named conf/input-booleans/
ios: !include conf/platforms/ios.yaml
mqtt: !include conf/platforms/mqtt.yaml
notion: !include conf/platforms/notion.yaml
notify: !include conf/platforms/notifiers.yaml
proximity: !include conf/platforms/proximity.yaml
wemo: !include conf/platforms/wemo.yaml
wwlln: !include conf/platforms/wwlln.yaml
zone: !include conf/zones.yaml
zwave: !include conf/platforms/zwave.yaml
