---
# Base Configuration:
homeassistant: !include conf/homeassistant.yaml

# Core Configuration
config:
frontend: !include conf/frontend.yaml
history:
http: !include conf/http.yaml
logbook:
logger: !include conf/logger.yaml
lovelace:
map:
panel_custom: !include conf/panel-custom.yaml
panel_iframe: !include conf/panel-iframe.yaml
recorder: !include conf/recorder.yaml
system_health:
updater:
zeroconf:

# Components:
cloud: !include_dir_merge_named conf/cloud/
emulated_hue: !include conf/platforms/emulated-hue.yaml
ffmpeg: !include conf/platforms/ffmpeg.yaml
group: !include_dir_named conf/groups/
ifttt: !include conf/platforms/ifttt.yaml
input_boolean: !include_dir_merge_named conf/input-booleans/
ios: !include conf/platforms/ios.yaml
mqtt: !include conf/platforms/mosquitto.yaml
nest: !include conf/platforms/nest.yaml
notify: !include conf/platforms/notifiers.yaml
proximity: !include conf/platforms/proximity.yaml
tts: !include conf/platforms/tts.yaml
wemo: !include conf/platforms/wemo.yaml
zone: !include conf/zones.yaml
zwave: !include conf/platforms/zwave.yaml
