---
api:
  # encryption:
  #   key: !secret api_encryption_key
  password: !secret api_password

binary_sensor:
  - name: ${device_friendly_name} Button
    on_press:
      - switch.toggle: relay
    pin:
      inverted: true
      number: GPIO0
    platform: gpio

  - name: ${device_friendly_name} Status
    platform: status

esphome:
  board: esp01_1m
  name: ${device_name}
  platform: ESP8266

logger:

ota:

status_led:
  pin:
    inverted: true
    number: GPIO13

switch:
  - id: relay
    name: ${device_friendly_name}
    pin: GPIO12
    platform: gpio

  - name: ${device_friendly_name} Restart
    platform: restart

text_sensor:
  - lambda: |-
      auto state = id(esphome_version).state;
      return state.substr(0, state.find(' '));
    name: "${device_friendly_name}: ESPHome Version (Short)"
    platform: template

  - id: esphome_version
    name: "${device_friendly_name}: ESPHome Version"
    platform: version

wifi:
  manual_ip:
    gateway: 172.16.20.1
    static_ip: ${device_static_ip}
    subnet: 255.255.255.0
  ssid: !secret wifi_ssid
  password: !secret wifi_password
