---
api:
  password: !secret api_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
    name: "Power Button"
    on_press:
      - switch.toggle: relay

  - platform: status
    name: "Gosund Smart Plug Status"

esphome:
  name: gosund_smart_plug
  platform: ESP8266
  board: esp8285

logger:

ota:

status_led:
  pin:
    number: GPIO1
    inverted: true

switch:
  - platform: gpio
    id: led
    pin: GPIO13
    inverted: true

  - platform: gpio
    name: "Gosund Smart Plug Smart Plug"
    pin: GPIO14
    id: relay
    on_turn_on:
      - switch.turn_on: led
    on_turn_off:
      - switch.turn_off: led

text_sensor:
  - platform: template
    name: "Gosund Smart Plug: ESPHome Version (Short)"
    lambda: |-
      auto state = id(esphome_version).state;
      return state.substr(0, state.find(' '));

  - platform: version
    name: "Gosund Smart Plug: ESPHome Version"
    id: esphome_version

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  output_power: 20dB
  manual_ip:
    static_ip: 172.16.11.65
    gateway: 172.16.11.1
    subnet: 255.255.255.0
