---
api:
  password: "password"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

  - platform: status
    name: "Master Bedroom Salt Lamp Status"

esphome:
  name: master_bedroom_salt_lamp
  platform: ESP8266
  board: esp01_1m

logger:

ota:

status_led:
  pin:
    number: GPIO13
    inverted: true

switch:
  - platform: gpio
    name: Master Bedroom Salt Lamp
    pin: GPIO12
    id: relay

  - platform: restart
    name: "Master Bedroom Salt Lamp Restart"

text_sensor:
  - platform: template
    name: "Master Bedroom Salt Lamp: ESPHome Version (Short)"
    lambda: |-
      auto state = id(version).state;
      return state.substr(0, state.find(' '));

  - platform: version
    name: "Master Bedroom Salt Lamp: ESPHome Version"
    id: version

wifi:
  ssid: "SSID"
  password: "password"
  fast_connect: true
  manual_ip:
    static_ip: 172.16.11.15
    gateway: 172.16.11.1
    subnet: 255.255.255.0
